### ISSUE TITLE
Broken external link for Team Workflow Article

### ISSUE THREAD

**Issue by salcode** [geeksam/think-like-a-git-dot-net#7]
The broken link appears on:
http://think-like-a-git.net/sections/rebase-from-the-ground-up.html
## Broken Link

http://johnwilger.com/blog/2011/01/08/production-release-workflow-with-git/
## Correct Link

http://johnwilger.com/2011/01/08/production-release-workflow-with-git.html

**Comment by geeksam** [comment]
apparently I fixed this in 2017 :D
